# Generated by Django 6.0.8 on 2026-09-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_superuser', 'Platform Superuser'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
